In [1]:
import numpy
import numpy as np

In [2]:
np

<module 'numpy' from 'D:\\PyProjects\\machine-learning-zoomcamp\\.venv\\Lib\\site-packages\\numpy\\__init__.py'>

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10, 2)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
a = np.array([1,2,3])

In [7]:
a

array([1, 2, 3])

In [8]:
a[2]

np.int64(3)

In [9]:
a[2] = 17

In [10]:
a

array([ 1,  2, 17])

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(7,12)

array([ 7,  8,  9, 10, 11])

In [13]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [14]:
np.linspace(12,55, 4)

array([12.        , 26.33333333, 40.66666667, 55.        ])

In [15]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [16]:
n = np.array([[1,2],[3,4],[5,6]])

In [17]:
n


array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
n[1][1] = 10

In [19]:
n

array([[ 1,  2],
       [ 3, 10],
       [ 5,  6]])

In [20]:
n[1] = [6, 8]

In [21]:
n

array([[1, 2],
       [6, 8],
       [5, 6]])

In [22]:
n[1,1]

np.int64(8)

In [23]:
n[:,1]

array([2, 8, 6])

In [24]:
n[:,0] = [9, 14, 22]

In [25]:
n

array([[ 9,  2],
       [14,  8],
       [22,  6]])

In [26]:
nr = np.random.rand(5,2)

In [27]:
nr

array([[0.64342152, 0.11301625],
       [0.5013914 , 0.84859589],
       [0.70075867, 0.47520027],
       [0.17041106, 0.52342711],
       [0.83912341, 0.84600517]])

In [28]:
nr

array([[0.64342152, 0.11301625],
       [0.5013914 , 0.84859589],
       [0.70075867, 0.47520027],
       [0.17041106, 0.52342711],
       [0.83912341, 0.84600517]])

In [29]:
nr = np.random.rand(5,2)


In [30]:
nr

array([[0.41007121, 0.93861378],
       [0.87589782, 0.38393908],
       [0.78386814, 0.0300924 ],
       [0.67593559, 0.10910653],
       [0.28746993, 0.27633533]])

In [31]:
np.random.randn(5,2)

array([[-0.21816252, -0.61564629],
       [-1.20079014,  0.51909721],
       [ 0.5401882 , -0.69689844],
       [-0.43655796,  1.42178036],
       [-0.42143359,  0.38343797]])

In [32]:
np.random.randint(low=0, high=99, size=(12,12))

array([[17, 22, 42, 57, 17, 68, 44,  3, 35, 76, 39, 75],
       [87, 65, 52,  2,  8, 37, 70, 49, 25, 97, 76, 54],
       [94, 85, 98, 56, 49, 77, 37, 15, 54, 12, 72, 61],
       [22,  7, 19, 38, 69,  3, 15, 62,  0, 42, 93, 12],
       [49, 16, 28, 86, 52, 35, 66, 88, 80, 89, 46, 53],
       [71, 58, 86, 34, 44, 38, 83,  5, 94, 76, 23, 28],
       [22, 34, 41, 83, 70, 21, 44, 18, 84,  3, 97,  4],
       [68, 68, 89, 58, 88, 72, 60, 64, 16, 28, 83, 61],
       [61, 39, 45, 85, 54, 60, 78, 56, 90, 11, 82, 28],
       [64, 23, 36, 10, 56, 62,  4,  8, 37, 63, 96, 27],
       [63, 84, 40, 49, 20, 91,  0, 23, 17, 14, 32, 57],
       [48, 81, 25,  0, 60, 62, 63, 71, 21, 23,  9, 64]], dtype=int32)

In [33]:
a = np.arange(5)

In [34]:
a

array([0, 1, 2, 3, 4])

In [35]:
a + 12

array([12, 13, 14, 15, 16])

In [36]:
b = (a * 2 + 120 / 12 + 2 ** 3)

In [37]:
b

array([18., 20., 22., 24., 26.])

In [38]:
a + b

array([18., 21., 24., 27., 30.])

In [39]:
a < b

array([ True,  True,  True,  True,  True])

In [40]:
a == 2

array([False, False,  True, False, False])

In [41]:
a[a == 2]

array([2])

In [42]:
a.min()

np.int64(0)

In [43]:
a.max()

np.int64(4)

In [44]:
a.sum

<function ndarray.sum(axis=None, dtype=None, out=None, **kwargs)>

In [45]:
a.sum()

np.int64(10)

In [46]:
n

array([[ 9,  2],
       [14,  8],
       [22,  6]])

In [47]:
a.std()

np.float64(1.4142135623730951)

In [48]:
n.std

<function ndarray.std(axis=None, dtype=None, out=None, ddof=0, **kwargs)>

In [49]:
n.std()

np.float64(6.3879226322456)

In [50]:
n.min(axis=1) #find min in each row

array([2, 8, 6])

In [51]:
n.min(axis=0) #find min in each column

array([9, 2])

In [52]:
u = np.array([2,4,5,6])

In [53]:
v = np.array([1,0,0,2])

In [54]:
np.dot(u, v) # dot product vector . vector
# dot product is used in algebra to find whether two vectors are close since
# a . b = |a||b|cos(f)
# if the lengths of both vectors are 1 then
# a . b = cos(f) <- the closer the dot product to 1 the more similar are the vectors in terms of direction

np.int64(14)

In [55]:
assert u.shape[0] == v.shape[0]
res = 0
for i in range(u.shape[0]):
    res += u[i] * v[i]

In [56]:
res

np.int64(14)

In [57]:
u.dot(v)

np.int64(14)

In [58]:
U = np.array([[2,4,5,6],[1,2,1,2],[3,1,2,1]])

In [59]:
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [60]:
U.dot(v)

array([14,  5,  5])

In [61]:
V = np.array([[1,1,2], [0,0.5,1], [0,2,1], [2,1,0]])

In [62]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [63]:
assert U.shape[1] == v.shape[0]
res = np.zeros(U.shape[0]) # fix
for i in range(U.shape[0]):
    res[i] = U[i].dot(v)

In [64]:
res

array([14.,  5.,  5.])

In [65]:
I = np.eye(4) # Identity matrix
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [66]:
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [67]:
U.dot(I)


array([[2., 4., 5., 6.],
       [1., 2., 1., 2.],
       [3., 1., 2., 1.]])

In [68]:
#inverse
Vs = V[[0,1,2]]

In [69]:
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [70]:
Vs_inv = np.linalg.inv(Vs)

In [71]:
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [72]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [73]:
import pandas as pd

In [74]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [75]:
data

[['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
 ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
 ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
 ['GMC', 'Acadia', 2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
 ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340]]

In [77]:
pd.DataFrame(data)

0         1     2      3  4          5            6      7
0   Nissan    Stanza  1991  138.0  4     MANUAL        sedan   2000
1  Hyundai    Sonata  2017    NaN  4  AUTOMATIC        Sedan  27150
2    Lotus     Elise  2010  218.0  4     MANUAL  convertible  54990
3      GMC    Acadia  2017  194.0  4  AUTOMATIC      4dr SUV  34450
4   Nissan  Frontier  2017  261.0  6     MANUAL       Pickup  32340

In [79]:
df = pd.DataFrame(data, columns=columns)

In [80]:
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [82]:
data = data = [
    {
        "Make": "Nissan",
        "Model": "Stanza",
        "Year": 1991,
        "Engine HP": 138.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "sedan",
        "MSRP": 2000
    },
    {
        "Make": "Hyundai",
        "Model": "Sonata",
        "Year": 2017,
        "Engine HP": None,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "Sedan",
        "MSRP": 27150
    },
    {
        "Make": "Lotus",
        "Model": "Elise",
        "Year": 2010,
        "Engine HP": 218.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "convertible",
        "MSRP": 54990
    },
    {
        "Make": "GMC",
        "Model": "Acadia",
        "Year": 2017,
        "Engine HP": 194.0,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "4dr SUV",
        "MSRP": 34450
    },
    {
        "Make": "Nissan",
        "Model": "Frontier",
        "Year": 2017,
        "Engine HP": 261.0,
        "Engine Cylinders": 6,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "Pickup",
        "MSRP": 32340
    }
]

In [83]:
data

[{'Make': 'Nissan',
  'Model': 'Stanza',
  'Year': 1991,
  'Engine HP': 138.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'sedan',
  'MSRP': 2000},
 {'Make': 'Hyundai',
  'Model': 'Sonata',
  'Year': 2017,
  'Engine HP': None,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': 'Sedan',
  'MSRP': 27150},
 {'Make': 'Lotus',
  'Model': 'Elise',
  'Year': 2010,
  'Engine HP': 218.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'convertible',
  'MSRP': 54990},
 {'Make': 'GMC',
  'Model': 'Acadia',
  'Year': 2017,
  'Engine HP': 194.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': '4dr SUV',
  'MSRP': 34450},
 {'Make': 'Nissan',
  'Model': 'Frontier',
  'Year': 2017,
  'Engine HP': 261.0,
  'Engine Cylinders': 6,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'Pickup',
  'MSRP': 32340}]

In [84]:
pd.DataFrame(data)

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [86]:
df.head(n=2)

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan  Stanza  1991      138.0                 4            MANUAL   
1  Hyundai  Sonata  2017        NaN                 4         AUTOMATIC   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150

In [87]:
df.Make

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: str

In [88]:
df["Make"]

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: str

In [89]:
df[["Make", "Model", "Year"]]

Make     Model  Year
0   Nissan    Stanza  1991
1  Hyundai    Sonata  2017
2    Lotus     Elise  2010
3      GMC    Acadia  2017
4   Nissan  Frontier  2017

In [90]:
df["id"] = [1,2,3,4,5]

In [91]:
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  id  
0         sedan   2000   1  
1         Sedan  27150   2  
2   convertible  54990   3  
3       4dr SUV  34450   4  
4        Pickup  32340   5

In [92]:
del df["id"]

In [93]:
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [94]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [95]:
df.Make.index

RangeIndex(start=0, stop=5, step=1)

In [96]:
df.loc[1]

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            Sedan
MSRP                     27150
Name: 1, dtype: object

In [97]:
df.loc[[1,2]]

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
1  Hyundai  Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus   Elise  2010      218.0                 4            MANUAL   

  Vehicle_Style   MSRP  
1         Sedan  27150  
2   convertible  54990

In [98]:
df.index = ["a", "b", "c", "d", "e"]

In [99]:
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
a   Nissan    Stanza  1991      138.0                 4            MANUAL   
b  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
c    Lotus     Elise  2010      218.0                 4            MANUAL   
d      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
e   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
a         sedan   2000  
b         Sedan  27150  
c   convertible  54990  
d       4dr SUV  34450  
e        Pickup  32340

In [100]:
df.loc["a"]

Make                 Nissan
Model                Stanza
Year                   1991
Engine HP             138.0
Engine Cylinders          4
Transmission Type    MANUAL
Vehicle_Style         sedan
MSRP                   2000
Name: a, dtype: object

In [101]:
df.iloc

In [102]:
df.iloc[[1,2,4]]

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
b  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
c    Lotus     Elise  2010      218.0                 4            MANUAL   
e   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
b         Sedan  27150  
c   convertible  54990  
e        Pickup  32340

In [106]:
df = df.reset_index(drop=True)

In [107]:
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [113]:
df["Engine HP"] / 100 * 2 ** 5

0    44.16
1      NaN
2    69.76
3    62.08
4    83.52
Name: Engine HP, dtype: float64

In [114]:
df["Year"] > 2010

0    False
1     True
2    False
3     True
4     True
Name: Year, dtype: bool

In [115]:
df[df["Year"] > 2010]

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
1         Sedan  27150  
3       4dr SUV  34450  
4        Pickup  32340

In [116]:
df[df["Make"] == "Nissan"]

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0  Nissan    Stanza  1991      138.0                 4            MANUAL   
4  Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
4        Pickup  32340

In [117]:
df[(df["Make"] == "Nissan") & (df["Year"] > 2010)]

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
4  Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
4        Pickup  32340

In [118]:
df["Vehicle_Style"]

0          sedan
1          Sedan
2    convertible
3        4dr SUV
4         Pickup
Name: Vehicle_Style, dtype: str

In [119]:
df = df["Vehicle_Style"].str.lower()

In [120]:
df

0          sedan
1          sedan
2    convertible
3        4dr suv
4         pickup
Name: Vehicle_Style, dtype: str

In [123]:
df = pd.DataFrame(data)

In [124]:
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [125]:
df["Vehicle_Style"].str.lower()

0          sedan
1          sedan
2    convertible
3        4dr suv
4         pickup
Name: Vehicle_Style, dtype: str

In [126]:
df["Vehicle_Style"].str.replace(" ", "_")

0          sedan
1          Sedan
2    convertible
3        4dr_SUV
4         Pickup
Name: Vehicle_Style, dtype: str

In [128]:
df["Vehicle_Style"] = df["Vehicle_Style"].str.replace(" ", "_").str.lower()

In [129]:
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         sedan  27150  
2   convertible  54990  
3       4dr_suv  34450  
4        pickup  32340

In [130]:
df.MSRP

0     2000
1    27150
2    54990
3    34450
4    32340
Name: MSRP, dtype: int64

In [131]:
df.MSRP.min()

np.int64(2000)

In [133]:
df.MSRP.describe()

count        5.000000
mean     30186.000000
std      18985.044904
min       2000.000000
25%      27150.000000
50%      32340.000000
75%      34450.000000
max      54990.000000
Name: MSRP, dtype: float64

In [135]:
df.describe().round(2)

Year  Engine HP  Engine Cylinders      MSRP
count     5.00       4.00              5.00      5.00
mean   2010.40     202.75              4.40  30186.00
std      11.26      51.30              0.89  18985.04
min    1991.00     138.00              4.00   2000.00
25%    2010.00     180.00              4.00  27150.00
50%    2017.00     206.00              4.00  32340.00
75%    2017.00     228.75              4.00  34450.00
max    2017.00     261.00              6.00  54990.00

In [137]:
df.Make.nunique()

4

In [138]:
df.nunique()

Make                 4
Model                5
Year                 3
Engine HP            4
Engine Cylinders     2
Transmission Type    2
Vehicle_Style        4
MSRP                 5
dtype: int64

In [139]:
df.isnull()

Make  Model   Year  Engine HP  Engine Cylinders  Transmission Type  \
0  False  False  False      False             False              False   
1  False  False  False       True             False              False   
2  False  False  False      False             False              False   
3  False  False  False      False             False              False   
4  False  False  False      False             False              False   

   Vehicle_Style   MSRP  
0          False  False  
1          False  False  
2          False  False  
3          False  False  
4          False  False

In [140]:
df.isnull().sum()

Make                 0
Model                0
Year                 0
Engine HP            1
Engine Cylinders     0
Transmission Type    0
Vehicle_Style        0
MSRP                 0
dtype: int64

In [141]:
df.groupby("Transmission Type").MSRP.mean()

Transmission Type
AUTOMATIC    30800.000000
MANUAL       29776.666667
Name: MSRP, dtype: float64

In [142]:
df.MSRP.values

array([ 2000, 27150, 54990, 34450, 32340])

In [143]:
df.to_dict(orient='records')

[{'Make': 'Nissan',
  'Model': 'Stanza',
  'Year': 1991,
  'Engine HP': 138.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'sedan',
  'MSRP': 2000},
 {'Make': 'Hyundai',
  'Model': 'Sonata',
  'Year': 2017,
  'Engine HP': nan,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': 'sedan',
  'MSRP': 27150},
 {'Make': 'Lotus',
  'Model': 'Elise',
  'Year': 2010,
  'Engine HP': 218.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'convertible',
  'MSRP': 54990},
 {'Make': 'GMC',
  'Model': 'Acadia',
  'Year': 2017,
  'Engine HP': 194.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': '4dr_suv',
  'MSRP': 34450},
 {'Make': 'Nissan',
  'Model': 'Frontier',
  'Year': 2017,
  'Engine HP': 261.0,
  'Engine Cylinders': 6,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'pickup',
  'MSRP': 32340}]